### ISSUE TITLE
Push notification not showing message tittle and  message body

### ISSUE THREAD

**Issue by adorufus** [CleverTap/clevertap-flutter#13] opened 2020-06-29 08:22 UTC
when i test send notification, it only show empty message

please help me

**Comment by darshanclevertap** [comment] 2020-07-17 06:23
@adorufus Sorry for the delay, can you tell us how are you testing sending of Push Notifications?

**Comment by darshanclevertap** [comment] 2020-07-21 12:56
@adorufus Can you explain how you have implemented Push Notifications? Also, are you testing on Android/iOS?

**Comment by ganeshrvel** [comment] 2020-08-20 16:11
@darshanclevertap I am also facing the same issue.

```shell
{notification: {title: null, body: null}, data: {wzrk_acct_id: 8WW-K46-795Z, nm: Message, nt: Test, pr: , wzrk_pivot: wzrk_default, wzrk_cid: channel_miscellaneous, wzrk_rnv: false, wzrk_ttl: 1598026099, wzrk_push_amp: false, wzrk_bc: , wzrk_bi: 2, wzrk_dt: FIREBASE, wzrk_id: 0_0, wzrk_pn: true}} ━━━━

```

<img width="721" alt="Screenshot 2020-08-20 at 9 40 52 PM" src="https://user-images.githubusercontent.com/182092/90797135-db453200-e32d-11ea-9ce3-85dfb8389738.png">

**Comment by ganeshrvel** [comment] 2020-08-20 17:14
I figured it out,
Add the below code in your `AndroidManifest.xml`

```xml
<application>
         ....
         ....
        <service android:name="com.clevertap.android.sdk.FcmTokenListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>

        <service android:name="com.clevertap.android.sdk.FcmMessageListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

 </application>
```

@darshanclevertap please add this to the clevertap for flutter sdk docs. There a lot of things which are missing in the docs regarding implementation and integration, also there is no clear documentation about the clevertap for flutter methods.

**Comment by darshanclevertap** [comment] 2020-08-21 02:58
@ganeshrvel We're in the process of revamping the documentation for all our hybrid platform SDKs, your feedback is duly noted and you'll be seeing a better version of the documentation soon. For my understanding, what do you mean by 

> there is no clear documentation about the clevertap for flutter methods.

Kindly explain so that we can add this to our list of things to improve.
Thanks!

**Comment by ayush221b** [comment] 2020-08-28 05:19
@darshanclevertap I have faced a similar issue, here are the details:

Platform tested on : **Android**

Plugin version: 1.1.2

**Context:**

We use firebase_messaging v7.0.0

The firebase messaging configure functions is done using this code:
```
_firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print(message);
        // Do something
      },
      onLaunch: (Map<String, dynamic> message) async {
       // Do something
       print(message);
      },
      onResume: (Map<String, dynamic> message) async {
        print(message);
      },
    );
```
We use multiple channels through which we receive push notifications in our app, Clevertap being one of them, we have followed the docs to configure clevertap and be ready to receive push notifications from clevertap.

**Issue**

When we do receive them, we get : 

```
{notification: {title: null, body: null}, data: {wzrk_acct_id: 8WW-K46-795Z, nm: Message, nt: Test, pr: , wzrk_pivot: wzrk_default, wzrk_cid: channel_miscellaneous, wzrk_rnv: false, wzrk_ttl: 1598026099, wzrk_push_amp: false, wzrk_bc: , wzrk_bi: 2, wzrk_dt: FIREBASE, wzrk_id: 0_0, wzrk_pn: true}}
```

exactly as @ganeshrvel pointed out, even when the title and message are provided in the clevertap dashboard.

A fix for this situation as already pointed  out is to add these lines in our AndroidManifest file:

```
<service android:name="com.clevertap.android.sdk.FcmTokenListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>

        <service android:name="com.clevertap.android.sdk.FcmMessageListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

But upon registering the following service:

```
<service android:name="com.clevertap.android.sdk.FcmMessageListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```
in our manifest, whenever we receive FCM notifications from a source channel other than Celevertap, and the app is in foreground, the `onMessage` callback does not even fire. Its almost as if the app ignores those notifications and does not receive them, `onLaunch` and `onResume` however continue to work in either case.

I can confirm that upon removing `com.clevertap.android.sdk.FcmMessageListenerService` service from our AndroidManifest, all three `firebase_messaging` callbacks do fire, but then again, we stop receiving the `title` and `body` key values in the notifications, as they are received as null.

Can you help us with the same?

Thanks

**Comment by darshanclevertap** [comment] 2020-08-28 07:34
@ayush221b I get your issue now. We always send Push Notification data as Firebase data messages so if you're seeing this payload - 

```
{notification: {title: null, body: null}, data: {wzrk_acct_id: 8WW-K46-795Z, nm: Message, nt: Test, pr: , wzrk_pivot: wzrk_default, wzrk_cid: channel_miscellaneous, wzrk_rnv: false, wzrk_ttl: 1598026099, wzrk_push_amp: false, wzrk_bc: , wzrk_bi: 2, wzrk_dt: FIREBASE, wzrk_id: 0_0, wzrk_pn: true}}
```

Then this is not an issue, since you have other Push services apart from CleverTap, what I can suggest you is you can use our `createNotification` method.

```
_firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print(message);
        cleverTap.createNotification(message.getData()); //pass the data object to us and we will handle the rendering of the push notification
      },
      onLaunch: (Map<String, dynamic> message) async {
       // Do something
       print(message);
      },
      onResume: (Map<String, dynamic> message) async {
        print(message);
      },
    );
```

You can find the reference to the `createNotification` method [here](https://github.com/CleverTap/clevertap-flutter/blob/master/lib/clevertap_plugin.dart#L320)

This way you don't need to add any Receivers/Services in the `AndroidManifest.xml` and use your other push channels/providers as well. 

@ganeshrvel I hope this helps you as well.

And I assure you, we will be fixing this in our upcoming documentation overhaul.
Also, **I would suggest updating to the latest version (1.1.4) as we fixed an important bug in the underlying core SDK**
Thank you

**Comment by ayush221b** [comment] 2020-08-28 07:37
Thank you so much for the quick response @darshanclevertap Will try this out.

**Comment by ayush221b** [comment] 2020-08-28 10:35
Hey @darshanclevertap I tried what you suggested.

App is in foreground. Platform is Android.

In my firebase_messaging configure method:
```
onMessage: (Map<String, dynamic> message) async {
        // When the app is open and it receives a push notification
              CleverTapPlugin.createNotification(jsonEncode(message['data']));
      },
```

I had tried to send `message['data']` directly but it threw an exception that said a HashMap could not be cast to a string, so I then opted for encoding the same in json.

In addition to that:

>This way you don't need to add any Receivers/Services in the AndroidManifest.xml and use your other push channels/providers as well.

I removed:

```
<service android:name="com.clevertap.android.sdk.FcmTokenListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>

        <service android:name="com.clevertap.android.sdk.FcmMessageListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

from my AndroidManifest.

Result:

The onMessage trigger worked, but there was no notification.

Console output:

```
E/FlutterFcmService( 2542): Fatal: failed to find callback
I/flutter ( 2542): ━━━━ Push notification 'onMessage' => {notification: {title: null, body: null}, data: {wzrk_acct_id: 8WW-K46-795Z, nm: I have arrived, nt: Hello ji, wzrk_pivot: wzrk_default, wzrk_cid: , wzrk_rnv: false, wzrk_ttl: 1598696943, wzrk_push_amp: false, wzrk_bc: , wzrk_bi: 2, wzrk_dt: FIREBASE, wzrk_id: 0_0, wzrk_pn: true}} ━━━━
I/flutter ( 2542): inside createNotification Dart
D/CleverTapPlugin( 2542): createNotification Android
```

So, the function I think was executed but then the notification did not appear.

**Comment by ayush221b** [comment] 2020-09-01 13:10
As suggested by Clevertap, I also added Channel id in the notification payload:

Console output:

```
I/flutter (14031): ━━━━ Push notification 'onMessage' => {notification: {title: null, body: null}, data: {wzrk_acct_id: 8WW-K46-795Z, nm: What's up, nt: Hello ji, wzrk_pivot: wzrk_default, wzrk_cid: Connect, wzrk_rnv: false, wzrk_ttl: 1599051890, wzrk_push_amp: false, wzrk_bc: , wzrk_bi: 2, wzrk_dt: FIREBASE, wzrk_id: 0_0, wzrk_pn: true}} ━━━━
I/flutter (14031): inside createNotification Dart
D/CleverTapPlugin(14031): createNotification Android
```

**Result: The notification still didn't appear.**

`onMessage` code:

```
onMessage: (Map<String, dynamic> message) async {
        // When the app is open and it receives a push notification
              CleverTapPlugin.createNotification(jsonEncode(message['data']));
      },
```

**Comment by darshanclevertap** [comment] 2020-09-02 04:16
@ayush221b Just to confirm, the Channel ID defined in the payload and the Channel ID defined on your app is the same?

**Comment by ayush221b** [comment] 2020-09-02 04:31
Yes, they are same

```
<meta-data
        android:name="com.google.firebase.messaging.default_notification_channel_id"
        android:value="Connect"/>
```

```
I/flutter (23832): ━━━━ Push notification 'onMessage' => {notification: {title: null, body: null}, data: {wzrk_acct_id: 8WW-K46-795Z, nm: Hey test body, nt: Hello, wzrk_pivot: wzrk_default, wzrk_cid: Connect, wzrk_rnv: false, wzrk_ttl: 1599107368, wzrk_push_amp: false, wzrk_bc: , wzrk_bi: 1, wzrk_dt: FIREBASE, wzrk_id: 0_0, wzrk_pn: true}} ━━━━
I/flutter (23832): inside createNotification Dart
D/CleverTapPlugin(23832): createNotification Android
```

**Comment by darshanclevertap** [comment] 2020-09-28 06:19
@ayush221b Sorry for the delay. Can you create your own channel ID using this [example here?](https://github.com/CleverTap/clevertap-flutter/blob/master/example/lib/main.dart#L29) And then use this channel ID to send your push notification?

**Comment by darshanclevertap** [comment] 2020-10-15 08:24
@ayush221b Did your issue get resolved?

**Comment by ayush221b** [comment] 2020-10-16 04:05
Yes, this was solved. Clevertap support helped us through it. In our case the only solution for firebase_messaging and clevertap to co-exist was to create a custom listener which handled clevertap and non-clevertap notifications separately.

**Closed** 2020-12-15 13:10 UTC
Labels: documentation

**Comment by epynic** [comment] 2021-04-20 09:51
> Yes, this was solved. Clevertap support helped us through it. In our case the only solution for firebase_messaging and clevertap to co-exist was to create a custom listener which handled clevertap and non-clevertap notifications separately.

Can you please share the custom listener ?
