### ISSUE TITLE
java.lang.ClassCastException: com.clevertap.android.sdk.Application cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by sanjayvramani** [CleverTap/clevertap-flutter#43] opened 2021-05-11 14:13 UTC
When i open the application or click on clevertap notification, i get error message like this:

E/CleverTapPlugin( 8259): Exception while running on main thread -
W/System.err( 8259): java.lang.ClassCastException: com.clevertap.android.sdk.Application cannot be cast to android.app.Activity
W/System.err( 8259): at com.clevertap.clevertap_plugin.CleverTapPlugin.runOnMainThread(CleverTapPlugin.java:1478)
W/System.err( 8259): at com.clevertap.clevertap_plugin.CleverTapPlugin.invokeMethodOnUiThread(CleverTapPlugin.java:1089)
W/System.err( 8259): at com.clevertap.clevertap_plugin.CleverTapPlugin.inboxDidInitialize(CleverTapPlugin.java:101)
W/System.err( 8259): at com.clevertap.android.sdk.CleverTapAPI._notifyInboxInitialized(CleverTapAPI.java:4171)
W/System.err( 8259): at com.clevertap.android.sdk.CleverTapAPI._initializeInbox(CleverTapAPI.java:4162)
W/System.err( 8259): at com.clevertap.android.sdk.CleverTapAPI.access$1600(CleverTapAPI.java:110)
W/System.err( 8259): at com.clevertap.android.sdk.CleverTapAPI$16.run(CleverTapAPI.java:2344)
W/System.err( 8259): at com.clevertap.android.sdk.CleverTapAPI$38.run(CleverTapAPI.java:6522)
W/System.err( 8259): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/System.err( 8259): at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 8259): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 8259): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 8259): at java.lang.Thread.run(Thread.java:919)

**Comment by darshanclevertap** [comment] 2021-05-12 16:57
@sanjayvramani Can you help us with the steps to reproduce this? Is this happening on every push notification or every app launch?

**Comment by sanjayvramani** [comment] 2021-05-13 06:33
I am getting this one on every app launch and every push notification click. I am using clever tap version 1.2.1 , flutter version 2.0.6 and firebase_messaging 9.1.3

**Comment by aldychris** [comment] 2021-05-17 05:33
Im also have this issue, it's always throw exception every time app laugh, push notification click or inAppNotification clicked. I'm using flutterEmbedding 2 on Android
```
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
            
```

**Comment by darshanclevertap** [comment] 2021-05-19 16:31
@sanjayvramani We'll be fixing this in the next release due Friday

**Comment by darshanclevertap** [comment] 2021-05-21 12:41
This has been fixed in CT Flutter Plugin v1.2.2

**Closed by darshanclevertap** 2021-05-21 12:41 UTC
Labels: under deployment

**Comment by arlakay** [comment] 2021-06-25 05:07
Hi, i got this issue to, i was try using 1.2.0 & 1.2.1 version
i can't update to 1.2.2 , because using flutter 1.22.6 dart version 2.10.5


I/flutter (12746): ╚══════════════════════════════════════════════════════════════════════════════════════════
V/CleverTap(12746): New Notification Inbox messages added
E/CleverTapPlugin(12746): Exception while running on main thread - 
W/System.err(12746): java.lang.ClassCastException: com.clevertap.android.sdk.Application cannot be cast to android.app.Activity
W/System.err(12746):    at com.clevertap.clevertap_plugin.CleverTapPlugin.runOnMainThread(CleverTapPlugin.java:1476)
W/System.err(12746):    at com.clevertap.clevertap_plugin.CleverTapPlugin.invokeMethodOnUiThread(CleverTapPlugin.java:1088)
W/System.err(12746):    at com.clevertap.clevertap_plugin.CleverTapPlugin.inboxMessagesDidUpdate(CleverTapPlugin.java:105)
W/System.err(12746):    at com.clevertap.android.sdk.CleverTapAPI$29.run(CleverTapAPI.java:4180)
W/System.err(12746):    at com.clevertap.android.sdk.Utils.runOnUiThread(Utils.java:71)
W/System.err(12746):    at com.clevertap.android.sdk.CleverTapAPI._notifyInboxMessagesDidUpdate(CleverTapAPI.java:4177)
W/System.err(12746):    at com.clevertap.android.sdk.CleverTapAPI._processInboxMessages(CleverTapAPI.java:4275)
W/System.err(12746):    at com.clevertap.android.sdk.CleverTapAPI.processInboxResponse(CleverTapAPI.java:6835)
W/System.err(12746):    at com.clevertap.android.sdk.CleverTapAPI.access$2000(CleverTapAPI.java:110)
W/System.err(12746):    at com.clevertap.android.sdk.CleverTapAPI$22.run(CleverTapAPI.java:3208)
W/System.err(12746):    at android.os.Handler.handleCallback(Handler.java:873)
W/System.err(12746):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(12746):    at android.os.Looper.loop(Looper.java:193)
W/System.err(12746):    at android.app.ActivityThread.main(ActivityThread.java:6692)
W/System.err(12746):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(12746):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(12746):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (12746): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by darshanclevertap** [comment] 2021-06-25 06:11
@arlakay Any reason why you cannot move to null safety as of now? v1.2.2 is the null safe version and Google is recommending that everyone move to the null safe version.

**Comment by arlakay** [comment] 2021-06-25 06:42
> @arlakay Any reason why you cannot move to null safety as of now? v1.2.2 is the null safe version and Google is recommending that everyone move to the null safe version.

hi, my project using many dependencies, to migrate to null safety i must update all the dependencies first , its takes time.
if i using 1.2.1 what must change to solve the error ?
